// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUepYZGgm3DyV81ZlqJhZ7P4ptqf9n9k',
    appId: '1:380373327086:web:2a6e2a73cfbe3b494067ff',
    messagingSenderId: '380373327086',
    projectId: 'hashim-store',
    authDomain: 'hashim-store.firebaseapp.com',
    storageBucket: 'hashim-store.appspot.com',
    measurementId: 'G-JRJHYHZDVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjfUmjz9DrU8A1G0zAve6tIbx5S61Bc4',
    appId: '1:380373327086:android:a78124e0411ab5904067ff',
    messagingSenderId: '380373327086',
    projectId: 'hashim-store',
    storageBucket: 'hashim-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQXXMYT5FpNFNd0Cu7WK4_W2lVtdUoJ8',
    appId: '1:380373327086:ios:cd605cceceb399374067ff',
    messagingSenderId: '380373327086',
    projectId: 'hashim-store',
    storageBucket: 'hashim-store.appspot.com',
    iosBundleId: 'com.example.hashimStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQXXMYT5FpNFNd0Cu7WK4_W2lVtdUoJ8',
    appId: '1:380373327086:ios:c27f5b7cf284bcdb4067ff',
    messagingSenderId: '380373327086',
    projectId: 'hashim-store',
    storageBucket: 'hashim-store.appspot.com',
    iosBundleId: 'com.example.hashimStore.RunnerTests',
  );
}
